version: '3'
services:
  web:
    image: httpd:2.4
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    networks:
      - frontend
      - backend
  backend:
    build: ./backend 
    container_name: backend
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - db 
    networks:
      - backend
      - frontend
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  db:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
        MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MARIADB_DATABASE: ${DB_NAME}
        MARIADB_USER: ${DB_USER}
        MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  
  
networks:
  frontend:
  backend:
volumes:
  db_data: